import React from "react";
import { HelpCircle, Send, RefreshCw, AlertCircle } from "lucide-react";

/**
 * QuestionCard - US-12 Developer Answer Interface
 *
 * Displays PR-specific questions generated by US-11 (via the backend RAG pipeline).
 * Each question shows: question text, category badge, related file badge,
 * supporting context snippet, and a dedicated textarea for the developer's answer.
 *
 * Props:
 *   questions       - Array of question objects from the backend (US-11 schema)
 *   answers         - Map of { [questionId]: answerText }
 *   onAnswerChange  - (questionId, value) => void — called on every keystroke
 *   onSubmitAnswers - () => void — called when developer submits all answers
 *   submitting      - boolean — disables submit while awaiting response
 *   submitError     - string | null — error message from failed submission
 *   submitSuccess   - boolean — true after a successful submission
 */
export default function QuestionCard({
  questions,
  answers,
  onAnswerChange,
  onSubmitAnswers,
  submitting,
  submitError,
  submitSuccess,
}) {
  if (!questions || questions.length === 0) {
    return (
      <div
        className="card-container"
        data-testid="no-questions-state"
        style={{ textAlign: "center", padding: "2rem", color: "#6b7280" }}
      >
        <HelpCircle size={32} style={{ margin: "0 auto 0.75rem", opacity: 0.4 }} />
        <p>No questions available for this PR yet.</p>
        <p style={{ fontSize: "0.8rem", marginTop: "0.25rem" }}>
          This can happen if the repository has not been indexed yet.
        </p>
      </div>
    );
  }

  const unansweredCount = questions.filter((q, idx) => {
    const id = q.id !== undefined ? q.id : idx;
    return !answers[id] || !answers[id].trim();
  }).length;

  const allAnswered = unansweredCount === 0;

  return (
    <div className="card-container" data-testid="question-card">
      {/* Header */}
      <div className="card-header-flex">
        <div className="card-header-left">
          <div className="card-header-icon text-purple">
            <HelpCircle size={20} />
          </div>
          <div>
            <h2 className="card-title">PR Understanding Questions</h2>
            <p className="card-description">
              Questions generated from RAG context to evaluate your comprehension of these PR changes.
            </p>
          </div>
        </div>

        {/* Unanswered counter badge */}
        {unansweredCount > 0 && (
          <span
            data-testid="unanswered-count"
            style={{
              backgroundColor: "#fef3c7",
              color: "#92400e",
              padding: "0.25rem 0.75rem",
              borderRadius: "999px",
              fontSize: "0.8rem",
              fontWeight: "bold",
              display: "flex",
              alignItems: "center",
              gap: "0.3rem",
            }}
          >
            <AlertCircle size={14} />
            {unansweredCount} unanswered
          </span>
        )}
      </div>

      {/* Questions list */}
      <div className="questions-list" data-testid="questions-list">
        {questions.map((q, idx) => {
          const id = q.id !== undefined ? q.id : idx;
          const currentAnswer = answers[id] || "";
          const isUnanswered = !currentAnswer.trim();

          return (
            <div
              key={id}
              className="question-item"
              data-testid={`question-item-${idx}`}
              style={{
                marginBottom: "1.5rem",
                borderLeft: isUnanswered ? "3px solid #fbbf24" : "3px solid #34d399",
                paddingLeft: "1rem",
              }}
            >
              {/* Question label */}
              <label
                htmlFor={`q-input-${id}`}
                className="question-label"
                style={{ display: "block", marginBottom: "0.5rem", fontWeight: "bold" }}
              >
                <span
                  className="question-number text-purple"
                  style={{ marginRight: "0.5rem" }}
                >
                  Q{idx + 1}.
                </span>
                {q.question}
              </label>

              {/* Metadata badges */}
              <div
                className="question-metadata"
                data-testid={`question-metadata-${idx}`}
                style={{ display: "flex", gap: "0.5rem", marginBottom: "0.75rem", flexWrap: "wrap" }}
              >
                {q.category && (
                  <span
                    data-testid={`category-badge-${idx}`}
                    style={{
                      backgroundColor: "#e0e7ff",
                      color: "#3730a3",
                      padding: "0.2rem 0.5rem",
                      borderRadius: "4px",
                      fontSize: "0.75rem",
                      fontWeight: "bold",
                    }}
                  >
                    {q.category.toUpperCase()}
                  </span>
                )}
                {q.related_file && (
                  <span
                    data-testid={`file-badge-${idx}`}
                    style={{
                      backgroundColor: "#f3f4f6",
                      color: "#374151",
                      padding: "0.2rem 0.5rem",
                      borderRadius: "4px",
                      fontSize: "0.75rem",
                      border: "1px solid #d1d5db",
                    }}
                  >
                    📄 {q.related_file}
                  </span>
                )}
                {/* Unanswered indicator */}
                {isUnanswered && (
                  <span
                    data-testid={`unanswered-indicator-${idx}`}
                    style={{ color: "#d97706", fontSize: "0.75rem", display: "flex", alignItems: "center", gap: "0.2rem" }}
                  >
                    <AlertCircle size={12} /> Unanswered
                  </span>
                )}
              </div>

              {/* Supporting context */}
              {q.supporting_context && (
                <div style={{ marginBottom: "0.75rem" }}>
                  <div style={{ fontSize: "0.75rem", color: "#6b7280", marginBottom: "0.25rem" }}>
                    Supporting Context:
                  </div>
                  <pre
                    data-testid={`supporting-context-${idx}`}
                    style={{
                      backgroundColor: "#f8fafc",
                      padding: "0.5rem",
                      borderRadius: "4px",
                      fontSize: "0.75rem",
                      overflowX: "auto",
                      border: "1px solid #e2e8f0",
                      color: "#475569",
                      whiteSpace: "pre-wrap",
                    }}
                  >
                    {q.supporting_context}
                  </pre>
                </div>
              )}

              {/* Answer textarea — uniquely bound to this question's id */}
              <textarea
                id={`q-input-${id}`}
                data-testid={`answer-input-${idx}`}
                data-question-id={id}
                className="text-area-input"
                style={{
                  width: "100%",
                  padding: "0.75rem",
                  borderRadius: "6px",
                  border: isUnanswered ? "1px solid #fbbf24" : "1px solid #34d399",
                  minHeight: "80px",
                  boxSizing: "border-box",
                  backgroundColor: "var(--bg-card, #fff)",
                  color: "var(--text-primary, #111)",
                }}
                placeholder={q.placeholder || "Enter your technical explanation here..."}
                value={currentAnswer}
                onChange={(e) => onAnswerChange(id, e.target.value)}
                aria-label={`Answer for question ${idx + 1}: ${q.question}`}
              />
            </div>
          );
        })}
      </div>

      {/* Submission feedback */}
      {submitError && (
        <div
          data-testid="submit-error"
          style={{
            backgroundColor: "#fee2e2",
            color: "#991b1b",
            padding: "0.75rem 1rem",
            borderRadius: "6px",
            marginBottom: "1rem",
            fontSize: "0.875rem",
          }}
        >
          <strong>Submission failed:</strong> {submitError}
        </div>
      )}

      {submitSuccess && (
        <div
          data-testid="submit-success"
          style={{
            backgroundColor: "#d1fae5",
            color: "#065f46",
            padding: "0.75rem 1rem",
            borderRadius: "6px",
            marginBottom: "1rem",
            fontSize: "0.875rem",
          }}
        >
          ✅ Answers submitted successfully! Proceeding to evaluation...
        </div>
      )}

      {/* Submit button */}
      <div className="submit-section">
        <button
          type="button"
          id="submit-answers-btn"
          data-testid="submit-answers-btn"
          onClick={onSubmitAnswers}
          disabled={submitting}
          className="btn-primary"
        >
          {submitting ? (
            <>
              <RefreshCw className="spin-icon" size={18} />
              <span>Submitting Answers...</span>
            </>
          ) : (
            <>
              <Send size={18} />
              <span>Submit Answers for Evaluation</span>
            </>
          )}
        </button>
      </div>
    </div>
  );
}
